language: ruby
rvm:
  - "2.0.0"

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate db:test:prepare

before_script:
  - psql -c 'create database sis_test;' -U postgres
